#!/bin/sh
# Cable test for LAN 2. See 'switch' for port mapping
usage="Usage cabletest:3 [-g|-s] [xml node] {value}"
vctfile="/var/run/port3.vct"
case "$1" in
"-g")
	case "$2" in
	"txstatus")
		[ -f "$vctfile" ] && scut -p 'TXSTATUS=' $vctfile
		;;
	"txmeter")
		[ -f "$vctfile" ] && scut -p 'TXMETER=' $vctfile
		;;
	"rxstatus")
		[ -f "$vctfile" ] && scut -p 'RXSTATUS=' $vctfile
		;;
	"rxmeter")
		[ -f "$vctfile" ] && scut -p 'RXMETER=' $vctfile
		;;
	esac
	;;
"-s")
	[ -f "$vctfile" ] && rm -f "$vctfile"
	ctest -i 2 > $vctfile
	rgdb -i -s /runtime/cabletest:3/txstatus	`scut -p 'TXSTATUS=' $vctfile`
	rgdb -i -s /runtime/cabletest:3/txmeter		`scut -p 'TXMETER=' $vctfile`
	rgdb -i -s /runtime/cabletest:3/rxstatus	`scut -p 'RXSTATUS=' $vctfile`
	rgdb -i -s /runtime/cabletest:3/rxmeter		`scut -p 'RXMETER=' $vctfile`
	;;
*)
	echo $usage
	;;
esac
