#!/bin/sh
# Cable test for LAN 3. See 'switch' for port mapping
usage="Usage cabletest:4 [-g|-s] [xml node] {value}"
vctfile="/var/run/port4.vct"
case "$1" in
"-g")
	case "$2" in
	"txstatus")
		[ -f "$vctfile" ] && scut -p 'TXSTATUS=' $vctfile
		;;
	"txmeter")
		[ -f "$vctfile" ] && scut -p 'TXMETER=' $vctfile
		;;
	"rxstatus")
		[ -f "$vctfile" ] && scut -p 'RXSTATUS=' $vctfile
		;;
	"rxmeter")
		[ -f "$vctfile" ] && scut -p 'RXMETER=' $vctfile
		;;
	esac
	;;
"-s")
	[ -f "$vctfile" ] && rm -f "$vctfile"
	ctest -i 1 > $vctfile
	rgdb -i -s /runtime/cabletest:4/txstatus	`scut -p 'TXSTATUS=' $vctfile`
	rgdb -i -s /runtime/cabletest:4/txmeter		`scut -p 'TXMETER=' $vctfile`
	rgdb -i -s /runtime/cabletest:4/rxstatus	`scut -p 'RXSTATUS=' $vctfile`
	rgdb -i -s /runtime/cabletest:4/rxmeter		`scut -p 'RXMETER=' $vctfile`
	;;
*)
	echo $usage
	;;
esac
