#!/bin/sh
#
# Port Mapping
# VZ-DI704	switch port
# ========	===========
# WAN		4
# LAN 1		3
# LAN 2		2
# LAN 3		1
# LAN 4		0
#
usage="Usage switch [-g] [xml node]"
case "$1" in
"-g")
	case "$2" in
	"port:1/linktype")
		psts -i 3
		;;
	"port:2/linktype")
		psts -i 2
		;;
	"port:3/linktype")
		psts -i 1
		;;
	"port:4/linktype")
		psts -i 0
		;;
	"wan_port")
		psts -i 4
		;;
	esac
	;;
"-s")
	if [ "$2" = "getlinktype" ]; then
		rgdb -i -s /runtime/switch/port:1/linktype "`psts -i 3`"
		rgdb -i -s /runtime/switch/port:2/linktype "`psts -i 2`"
		rgdb -i -s /runtime/switch/port:3/linktype "`psts -i 1`"
		rgdb -i -s /runtime/switch/port:4/linktype "`psts -i 0`"
		rgdb -i -s /runtime/wan/inf:1/linktype "`psts -i 4`"
	fi
	;;
*)
	echo $usage
	;;
esac
