<?
/* Generate resolv.conf according to the runtime nodes. */
$RFILE = "/etc/resolv.conf";
fwrite($RFILE, "# This file is generated by gen_resolv.php\n");
$dns=query("/runtime/wan/inf:1/primarydns");	if ($dns!=""){fwrite2($RFILE, "nameserver ".$dns."\n");}
$dns=query("/runtime/wan/inf:1/secondarydns");	if ($dns!=""){fwrite2($RFILE, "nameserver ".$dns."\n");}
$dns=query("/runtime/wan/inf:2/primarydns");	if ($dns!=""){fwrite2($RFILE, "nameserver ".$dns."\n");}
$dns=query("/runtime/wan/inf:2/secondarydns");	if ($dns!=""){fwrite2($RFILE, "nameserver ".$dns."\n");}
?>
