# keep_alive_run.php >>>
<? /* vi: set sw=4 ts=4: */

//if( $keep_alive_script_file == "" )
//{ $keep_alive_script_file = "/var/run/keep_alive.sh"; }
//if( $keep_alive_ping_dst_1 == "" )
//{ $keep_alive_ping_dst_1 = "www.google.com"; }
//if( $keep_alive_ping_dst_2 == "" )
//{ $keep_alive_ping_dst_2 = ""; }
//if( $keep_alive_sleep_interval == "" )
//{ $keep_alive_sleep_interval = 60; }

if( $keep_alive_ping_dst_2 != "" )
{
	$dst_2_indentation = "\t";
}	
else
{
	$dst_2_indentation = "";
}

/* header */
fwrite( $keep_alive_script_file, "#!/bin/sh\n");
fwrite2($keep_alive_script_file, "# Generated by keep_alive_run.php");
fwrite2($keep_alive_script_file, "echo [$0] ... > /dev/console\n");
fwrite2($keep_alive_script_file, "echo \"[$0] Start Keep-alive ping loop ...\" > /dev/console\n");
fwrite2($keep_alive_script_file, "\n");

/* variable declaration */
fwrite2($keep_alive_script_file, "ping_destination_1=".$keep_alive_ping_dst_1."\n");
if( $keep_alive_ping_dst_2 != "" )
{ 
	fwrite2($keep_alive_script_file, "ping_destination_2=".$keep_alive_ping_dst_2."\n"); 
}
fwrite2($keep_alive_script_file, "sleep_int=".$keep_alive_sleep_interval."\n");
fwrite2($keep_alive_script_file, "loop_index=1\n");
fwrite2($keep_alive_script_file, "num_fail=0\n");
fwrite2($keep_alive_script_file, "\n");

/* sleep for 60 seconds for the initial WAN connection to connect */
fwrite2($keep_alive_script_file, "sleep 60\n");

/* ping loop test */
/* we only ping test with ttl as 3, 4, 5 so we don't spam the server */
fwrite2($keep_alive_script_file, "while [ $loop_index = 1 ]; do\n");
fwrite2($keep_alive_script_file, "ping_result_1=`ping -t 3 $ping_destination_1`\n");
fwrite2($keep_alive_script_file, "ping_result_2=`ping -t 4 $ping_destination_1`\n");
fwrite2($keep_alive_script_file, "ping_result_3=`ping -t 5 $ping_destination_1`\n");
fwrite2($keep_alive_script_file, "if [ \"$ping_result_1\" != \"Time to live exceeded!\" ] && [ \"$ping_result_1\" != \"$ping_destination_1 is alive!\" ] ");
fwrite2($keep_alive_script_file, "&& [ \"$ping_result_2\" != \"Time to live exceeded!\" ] && [ \"$ping_result_2\" != \"$ping_destination_1 is alive!\" ] ");
fwrite2($keep_alive_script_file, "&& [ \"$ping_result_3\" != \"Time to live exceeded!\" ] && [ \"$ping_result_3\" != \"$ping_destination_1 is alive!\" ]; then\n");
if( $keep_alive_ping_dst_2 != "" )
{
	fwrite2($keep_alive_script_file, "\tping_result_1=`ping -t 3 $ping_destination_2`\n");
	fwrite2($keep_alive_script_file, "\tping_result_2=`ping -t 4 $ping_destination_2`\n");
	fwrite2($keep_alive_script_file, "\tping_result_3=`ping -t 5 $ping_destination_2`\n");
	fwrite2($keep_alive_script_file, "\tif [ \"$ping_result_1\" != \"Time to live exceeded!\" ] && [ \"$ping_result_1\" != \"$ping_destination_1 is alive!\" ] ");
	fwrite2($keep_alive_script_file, "\t&& [ \"$ping_result_2\" != \"Time to live exceeded!\" ] && [ \"$ping_result_2\" != \"$ping_destination_1 is alive!\" ] ");
	fwrite2($keep_alive_script_file, "\t&& [ \"$ping_result_3\" != \"Time to live exceeded!\" ] && [ \"$ping_result_3\" != \"$ping_destination_1 is alive!\" ]; then\n");
}
fwrite2($keep_alive_script_file, $dst_2_indentation."\techo \"[$0] ping failure detected!\"\n");
fwrite2($keep_alive_script_file, $dst_2_indentation."\tcase \"$num_fail\" in\n");
fwrite2($keep_alive_script_file, $dst_2_indentation."\t0)\n");
fwrite2($keep_alive_script_file, $dst_2_indentation."\t\tnum_fail=1\n");
fwrite2($keep_alive_script_file, $dst_2_indentation."\t\t;;\n");
fwrite2($keep_alive_script_file, $dst_2_indentation."\t1)\n");
fwrite2($keep_alive_script_file, $dst_2_indentation."\t\tnum_fail=2\n");
fwrite2($keep_alive_script_file, $dst_2_indentation."\t\t;;\n");
fwrite2($keep_alive_script_file, $dst_2_indentation."\t2)\n");
fwrite2($keep_alive_script_file, $dst_2_indentation."\t\tnum_fail=3\n");
fwrite2($keep_alive_script_file, $dst_2_indentation."\t\t;;\n");
fwrite2($keep_alive_script_file, $dst_2_indentation."\t3)\n");
fwrite2($keep_alive_script_file, $dst_2_indentation."\t\tnum_fail=4\n");
fwrite2($keep_alive_script_file, $dst_2_indentation."\t\t;;\n");
fwrite2($keep_alive_script_file, $dst_2_indentation."\t*)\n");
fwrite2($keep_alive_script_file, $dst_2_indentation."\t\techo \"consecutive failure attempts exceeds 4 tries\"\n");
fwrite2($keep_alive_script_file, $dst_2_indentation."\t\t;;\n");
fwrite2($keep_alive_script_file, $dst_2_indentation."\tesac\n");
if( $keep_alive_ping_dst_2 != "" )
{
	fwrite2($keep_alive_script_file, "\telse\n");
	fwrite2($keep_alive_script_file, "\t\tnum_fail=0\n");
	fwrite2($keep_alive_script_file, "\tfi\n"); /* endif for destination 2 ping test */
}	
fwrite2($keep_alive_script_file, "else\n");
fwrite2($keep_alive_script_file, "\tnum_fail=0\n");
fwrite2($keep_alive_script_file, "\techo \"[$0] WAN Connection still alive!\"\n");
fwrite2($keep_alive_script_file, "fi\n"); /* endif for destination 1 ping test */
fwrite2($keep_alive_script_file, "\n");

/* cases to break out of the loop */
/* assume failed consecutively for more than 3 times means we lost the WAN connection */
fwrite2($keep_alive_script_file, "if [ $num_fail -gt 3 ]; then\n");
fwrite2($keep_alive_script_file, "\tloop_index=0\n");
fwrite2($keep_alive_script_file, "\techo \"[$0] consecutive failure attempts exceeds 3 tries\"\n");
fwrite2($keep_alive_script_file, "\tsubmit WAN\n"); /* restart WAN */
fwrite2($keep_alive_script_file, "fi\n");
fwrite2($keep_alive_script_file, "\n");

/* sleep for designated interval of seconds */
/* skip sleeping process if we already got failed attempts */
fwrite2($keep_alive_script_file, "if [ $num_fail = 0 ]; then\n");
fwrite2($keep_alive_script_file, "\tsleep $sleep_int\n");
fwrite2($keep_alive_script_file, "fi\n");
fwrite2($keep_alive_script_file, "\n");

/* end of infinite while loop */
fwrite2($keep_alive_script_file, "done\n"); 
fwrite2($keep_alive_script_file, "\n");
 
?># keep_alive_run.php <<<

