#!/bin/sh
# Start all init scripts in /etc/init.d
# executing them in numerical order.
# allow scripts to continue running after rcS completes

for i in /etc/init.d/S??* ;do
	# Ignore dangling symlinks (if any).
	[ ! -f "$i" ] && continue
	case "$i" in
	*.sh)
		# Source shell script for speed.
		echo "[$i]"
		$i start
		echo "[$i] done!"
		;;
	*)
		# No sh extension, so fork subprocess.
		$i start
		;;
	esac
done
echo "rcS done!"
